import type { Metadata } from "next";
import {Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang={'ko'}>
      <head/>
      <body className="m-0">
      <div className={`min-h-screen mx-auto bg-white ${montserrat.className} w-full mob:w-[880px]`}>
          <div className="flex flex-1 flex-col">
              <Header/>
              {children}
              <Footer />
          </div>
      </div>
      </body>
      </html>
);
}
