import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import Providers from '@/foo/provider';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={'ko'}>
      <head />
      <body className="m-0 bg-gray900">
        <div
          className={`min-h-screen mx-auto ${montserrat.className} w-full mob:w-[880px]`}
        >
          <div className="flex flex-1 flex-col">
            <Providers>
              <Header />
              {children}
              <Footer />
            </Providers>
          </div>
        </div>
      </body>
    </html>
  );
}
